In [1]:
import pandas as pd
import re

In [10]:
wld=pd.read_csv('World_dev.csv')
wld.shape

(247, 31)

In [3]:
wld.head(10)

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2013.0,2000.0
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011.0,2013.0,2006.0
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,NaN,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",NaN,NaN,2010.0,2013.0,2001.0
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN
5,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),2014,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008/09",NaN,2015,NaN,NaN,2005.0
6,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,April 2012 database update: Based on official ...,Latin America & Caribbean,High income: nonOECD,AG,...,Budgetary central government,General Data Dissemination System (GDDS),2011,NaN,NaN,Yes,2007,NaN,2013.0,2005.0
7,ARB,Arab World,Arab World,Arab World,1A,NaN,Arab World aggregate. Arab World is composed o...,NaN,NaN,1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,The base year has changed to 2004.,Latin America & Caribbean,High income: nonOECD,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2013.0,2011.0
9,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Lower middle income,AM,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey (DHS), 2010","Integrated household survey (IHS), 2012",Yes,2013/14,2008.0,2013.0,2012.0

In [11]:
hpns=pd.read_csv('World_Happiness_2015.csv')
hpns.shape

(158, 12)

In [16]:
y=pd.merge(left=hpns,right=wld,how='left',left_on='Country',right_on='ShortName')
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 0 to 157
Data columns (total 43 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     158 non-null    object
 1   Region_x                                    158 non-null    object
 2   Happiness Rank                              158 non-null    int64
 3   Happiness Score                             158 non-null    float64
 4   Standard Error                              158 non-null    float64
 5   Economy (GDP per Capita)                    158 non-null    float64
 6   Family                                      158 non-null    float64
 7   Health (Life Expectancy)                    158 non-null    float64
 8   Freedom                                     158 non-null    float64
 9   Trust (Government Corruption)               158 non-null    float64
 10  Generosity                                  158 non-null    float64
 11  Dystopia Residual                           158 non-null    float64
 12  CountryCode                                 145 non-null    object
 13  ShortName                                   145 non-null    object
 14  TableName                                   145 non-null    object
 15  LongName                                    145 non-null    object
 16  Alpha2Code                                  144 non-null    object
 17  CurrencyUnit                                145 non-null    object
 18  SpecialNotes                                93 non-null     object
 19  Region_y                                    145 non-null    object
 20  IncomeGroup                                 145 non-null    object
 21  Wb2Code                                     145 non-null    object
 22  NationalAccountsBaseYear                    145 non-null    object
 23  NationalAccountsReferenceYear               48 non-null     object
 24  SnaPriceValuation                           145 non-null    object
 25  LendingCategory                             106 non-null    object
 26  OtherGroups                                 48 non-null     object
 27  SystemOfNationalAccounts                    145 non-null    object
 28  AlternativeConversionFactor                 40 non-null     object
 29  PppSurveyYear                               139 non-null    object
 30  BalanceOfPaymentsManualInUse                141 non-null    object
 31  ExternalDebtReportingStatus                 98 non-null     object
 32  SystemOfTrade                               143 non-null    object
 33  GovernmentAccountingConcept                 128 non-null    object
 34  ImfDataDisseminationStandard                142 non-null    object
 35  LatestPopulationCensus                      145 non-null    object
 36  LatestHouseholdSurvey                       115 non-null    object
 37  SourceOfMostRecentIncomeAndExpenditureData  130 non-null    object
 38  VitalRegistrationComplete                   73 non-null     object
 39  LatestAgriculturalCensus                    116 non-null    object
 40  LatestIndustrialData                        99 non-null     float64
 41  LatestTradeData                             139 non-null    float64
 42  LatestWaterWithdrawalData                   144 non-null    float64
dtypes: float64(12), int64(1), object(30)
memory usage: 54.3+ KB

In [19]:
col={'SourceOfMostRecentIncomeAndExpenditureData':'iesurvey'}
y=y.rename(col,axis=1)
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 0 to 157
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region_x                       158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
 12  CountryCode                    145 non-null    object
 13  ShortName                      145 non-null    object
 14  TableName                      145 non-null    object
 15  LongName                       145 non-null    object
 16  Alpha2Code                     144 non-null    object
 17  CurrencyUnit                   145 non-null    object
 18  SpecialNotes                   93 non-null     object
 19  Region_y                       145 non-null    object
 20  IncomeGroup                    145 non-null    object
 21  Wb2Code                        145 non-null    object
 22  NationalAccountsBaseYear       145 non-null    object
 23  NationalAccountsReferenceYear  48 non-null     object
 24  SnaPriceValuation              145 non-null    object
 25  LendingCategory                106 non-null    object
 26  OtherGroups                    48 non-null     object
 27  SystemOfNationalAccounts       145 non-null    object
 28  AlternativeConversionFactor    40 non-null     object
 29  PppSurveyYear                  139 non-null    object
 30  BalanceOfPaymentsManualInUse   141 non-null    object
 31  ExternalDebtReportingStatus    98 non-null     object
 32  SystemOfTrade                  143 non-null    object
 33  GovernmentAccountingConcept    128 non-null    object
 34  ImfDataDisseminationStandard   142 non-null    object
 35  LatestPopulationCensus         145 non-null    object
 36  LatestHouseholdSurvey          115 non-null    object
 37  iesurvey                       130 non-null    object
 38  VitalRegistrationComplete      73 non-null     object
 39  LatestAgriculturalCensus       116 non-null    object
 40  LatestIndustrialData           99 non-null     float64
 41  LatestTradeData                139 non-null    float64
 42  LatestWaterWithdrawalData      144 non-null    float64
dtypes: float64(12), int64(1), object(30)
memory usage: 54.3+ KB

In [22]:
y['CurrencyUnit'].head(20)

0            Swiss franc
1          Iceland krona
2           Danish krone
3        Norwegian krone
4        Canadian dollar
5                   Euro
6                   Euro
7          Swedish krona
8     New Zealand dollar
9      Australian dollar
10    Israeli new shekel
11     Costa Rican colon
12                  Euro
13          Mexican peso
14           U.S. dollar
15        Brazilian real
16                  Euro
17                  Euro
18                  Euro
19         U.A.E. dirham
Name: CurrencyUnit, dtype: object

In [25]:
def cur(i):
    return str(i).split()[-1]

In [26]:
y['currency']=y['CurrencyUnit'].apply(cur)
y['currency'].head()

0     franc
1     krona
2     krone
3     krone
4    dollar
Name: currency, dtype: object

In [28]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 0 to 157
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region_x                       158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
 12  CountryCode                    145 non-null    object
 13  ShortName                      145 non-null    object
 14  TableName                      145 non-null    object
 15  LongName                       145 non-null    object
 16  Alpha2Code                     144 non-null    object
 17  CurrencyUnit                   145 non-null    object
 18  SpecialNotes                   93 non-null     object
 19  Region_y                       145 non-null    object
 20  IncomeGroup                    145 non-null    object
 21  Wb2Code                        145 non-null    object
 22  NationalAccountsBaseYear       145 non-null    object
 23  NationalAccountsReferenceYear  48 non-null     object
 24  SnaPriceValuation              145 non-null    object
 25  LendingCategory                106 non-null    object
 26  OtherGroups                    48 non-null     object
 27  SystemOfNationalAccounts       145 non-null    object
 28  AlternativeConversionFactor    40 non-null     object
 29  PppSurveyYear                  139 non-null    object
 30  BalanceOfPaymentsManualInUse   141 non-null    object
 31  ExternalDebtReportingStatus    98 non-null     object
 32  SystemOfTrade                  143 non-null    object
 33  GovernmentAccountingConcept    128 non-null    object
 34  ImfDataDisseminationStandard   142 non-null    object
 35  LatestPopulationCensus         145 non-null    object
 36  LatestHouseholdSurvey          115 non-null    object
 37  iesurvey                       130 non-null    object
 38  VitalRegistrationComplete      73 non-null     object
 39  LatestAgriculturalCensus       116 non-null    object
 40  LatestIndustrialData           99 non-null     float64
 41  LatestTradeData                139 non-null    float64
 42  LatestWaterWithdrawalData      144 non-null    float64
 43  currency                       158 non-null    object
dtypes: float64(12), int64(1), object(31)
memory usage: 60.5+ KB

In [24]:
y['CurrencyUnit'][0].split()[-1]

'franc'

In [32]:
y['CurrencyUnit'].str[-4:-1]

0      ran
1      ron
2      ron
3      ron
4      lla
      ...
153    ran
154    ran
155    NaN
156    ran
157    ran
Name: CurrencyUnit, Length: 158, dtype: object

In [1]:
y['Happiness Score'].isnull()

NameError: name 'y' is not defined