In [13]:
import pandas as pd
import re

In [2]:
hpns1=pd.read_csv('World_Happiness_2015.csv')

In [3]:
hpns2=pd.read_csv('World_Happiness_2016.csv')

In [4]:
hpns3=pd.read_csv('World_Happiness_2017 (1).csv')

In [10]:
y=pd.merge(pd.merge(hpns1,hpns2,on='Country'),hpns3,on='Country')
y

,Country,Region_x,Happiness Rank_x,Happiness Score_x,Standard Error,Economy (GDP per Capita)_x,Family_x,Health (Life Expectancy)_x,Freedom_x,Trust (Government Corruption)_x,...,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,7.316,7.384403,7.247597,1.479204,1.481349,0.834558,0.611101,0.435540,0.287372,2.187264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,...,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
142,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,...,3.657,3.745784,3.568217,0.431085,0.435300,0.209930,0.425963,0.207948,0.060929,1.885631
143,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,...,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
144,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,...,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
145,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,...,3.495,3.594038,3.395962,0.305445,0.431883,0.247106,0.380426,0.196896,0.095665,1.837229

In [11]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 0 to 145
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          146 non-null    object
 1   Region_x                         146 non-null    object
 2   Happiness Rank_x                 146 non-null    int64
 3   Happiness Score_x                146 non-null    float64
 4   Standard Error                   146 non-null    float64
 5   Economy (GDP per Capita)_x       146 non-null    float64
 6   Family_x                         146 non-null    float64
 7   Health (Life Expectancy)_x       146 non-null    float64
 8   Freedom_x                        146 non-null    float64
 9   Trust (Government Corruption)_x  146 non-null    float64
 10  Generosity_x                     146 non-null    float64
 11  Dystopia Residual_x              146 non-null    float64
 12  Region_y                         146 non-null    object
 13  Happiness Rank_y                 146 non-null    int64
 14  Happiness Score_y                146 non-null    float64
 15  Lower Confidence Interval        146 non-null    float64
 16  Upper Confidence Interval        146 non-null    float64
 17  Economy (GDP per Capita)_y       146 non-null    float64
 18  Family_y                         146 non-null    float64
 19  Health (Life Expectancy)_y       146 non-null    float64
 20  Freedom_y                        146 non-null    float64
 21  Trust (Government Corruption)_y  146 non-null    float64
 22  Generosity_y                     146 non-null    float64
 23  Dystopia Residual_y              146 non-null    float64
 24  Happiness.Rank                   146 non-null    int64
 25  Happiness.Score                  146 non-null    float64
 26  Whisker.high                     146 non-null    float64
 27  Whisker.low                      146 non-null    float64
 28  Economy..GDP.per.Capita.         146 non-null    float64
 29  Family                           146 non-null    float64
 30  Health..Life.Expectancy.         146 non-null    float64
 31  Freedom                          146 non-null    float64
 32  Generosity                       146 non-null    float64
 33  Trust..Government.Corruption.    146 non-null    float64
 34  Dystopia.Residual                146 non-null    float64
dtypes: float64(29), int64(3), object(3)
memory usage: 41.1+ KB

In [19]:
col=y.loc[:,['Region_y']]
x=re.findall('Western Europe',col)

TypeError: expected string or bytes-like object

In [21]:
col=y.loc[:,['Region_y']]

                            Region_y
0                     Western Europe
1                     Western Europe
2                     Western Europe
3                     Western Europe
4                      North America
..                               ...
141               Sub-Saharan Africa
142               Sub-Saharan Africa
143  Middle East and Northern Africa
144               Sub-Saharan Africa
145               Sub-Saharan Africa

[146 rows x 1 columns]

aaa=y.groupby('Region_x')
bbb=aaa.get_group('Sub-Saharan Africa')
bbb

In [30]:
bbb1=bbb.loc[:,'Country']
bbb1

67               Mauritius
73                 Nigeria
80                  Zambia
103           South Africa
104                  Ghana
105               Zimbabwe
106                Liberia
108                  Sudan
110       Congo (Kinshasa)
112               Ethiopia
113           Sierra Leone
114             Mauritania
115                  Kenya
117               Botswana
120                 Malawi
122               Cameroon
126                 Angola
127                   Mali
128    Congo (Brazzaville)
129                 Uganda
130                Senegal
131                  Gabon
132                  Niger
134               Tanzania
135             Madagascar
136                   Chad
137                 Guinea
138            Ivory Coast
139           Burkina Faso
141                 Rwanda
142                  Benin
144                Burundi
145                   Togo
Name: Country, dtype: object

In [41]:
column={'Region_x':'region'}
bbb1=y.rename(column,axis=1)
bbb1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 0 to 145
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          146 non-null    object
 1   region                           146 non-null    object
 2   Happiness Rank_x                 146 non-null    int64
 3   Happiness Score_x                146 non-null    float64
 4   Standard Error                   146 non-null    float64
 5   Economy (GDP per Capita)_x       146 non-null    float64
 6   Family_x                         146 non-null    float64
 7   Health (Life Expectancy)_x       146 non-null    float64
 8   Freedom_x                        146 non-null    float64
 9   Trust (Government Corruption)_x  146 non-null    float64
 10  Generosity_x                     146 non-null    float64
 11  Dystopia Residual_x              146 non-null    float64
 12  Region_y                         146 non-null    object
 13  Happiness Rank_y                 146 non-null    int64
 14  Happiness Score_y                146 non-null    float64
 15  Lower Confidence Interval        146 non-null    float64
 16  Upper Confidence Interval        146 non-null    float64
 17  Economy (GDP per Capita)_y       146 non-null    float64
 18  Family_y                         146 non-null    float64
 19  Health (Life Expectancy)_y       146 non-null    float64
 20  Freedom_y                        146 non-null    float64
 21  Trust (Government Corruption)_y  146 non-null    float64
 22  Generosity_y                     146 non-null    float64
 23  Dystopia Residual_y              146 non-null    float64
 24  Happiness.Rank                   146 non-null    int64
 25  Happiness.Score                  146 non-null    float64
 26  Whisker.high                     146 non-null    float64
 27  Whisker.low                      146 non-null    float64
 28  Economy..GDP.per.Capita.         146 non-null    float64
 29  Family                           146 non-null    float64
 30  Health..Life.Expectancy.         146 non-null    float64
 31  Freedom                          146 non-null    float64
 32  Generosity                       146 non-null    float64
 33  Trust..Government.Corruption.    146 non-null    float64
 34  Dystopia.Residual                146 non-null    float64
dtypes: float64(29), int64(3), object(3)
memory usage: 41.1+ KB

In [54]:
pattern=r'([i][a])'
col2=y['Country'].str.extract(pattern)

In [56]:
y['col2']=col2
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 0 to 145
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          146 non-null    object
 1   Region_x                         146 non-null    object
 2   Happiness Rank_x                 146 non-null    int64
 3   Happiness Score_x                146 non-null    float64
 4   Standard Error                   146 non-null    float64
 5   Economy (GDP per Capita)_x       146 non-null    float64
 6   Family_x                         146 non-null    float64
 7   Health (Life Expectancy)_x       146 non-null    float64
 8   Freedom_x                        146 non-null    float64
 9   Trust (Government Corruption)_x  146 non-null    float64
 10  Generosity_x                     146 non-null    float64
 11  Dystopia Residual_x              146 non-null    float64
 12  Region_y                         146 non-null    object
 13  Happiness Rank_y                 146 non-null    int64
 14  Happiness Score_y                146 non-null    float64
 15  Lower Confidence Interval        146 non-null    float64
 16  Upper Confidence Interval        146 non-null    float64
 17  Economy (GDP per Capita)_y       146 non-null    float64
 18  Family_y                         146 non-null    float64
 19  Health (Life Expectancy)_y       146 non-null    float64
 20  Freedom_y                        146 non-null    float64
 21  Trust (Government Corruption)_y  146 non-null    float64
 22  Generosity_y                     146 non-null    float64
 23  Dystopia Residual_y              146 non-null    float64
 24  Happiness.Rank                   146 non-null    int64
 25  Happiness.Score                  146 non-null    float64
 26  Whisker.high                     146 non-null    float64
 27  Whisker.low                      146 non-null    float64
 28  Economy..GDP.per.Capita.         146 non-null    float64
 29  Family                           146 non-null    float64
 30  Health..Life.Expectancy.         146 non-null    float64
 31  Freedom                          146 non-null    float64
 32  Generosity                       146 non-null    float64
 33  Trust..Government.Corruption.    146 non-null    float64
 34  Dystopia.Residual                146 non-null    float64
 35  col2                             35 non-null     object
dtypes: float64(29), int64(3), object(4)
memory usage: 42.2+ KB

In [59]:
y['Happiness Score_x'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
141    False
142    False
143    False
144    False
145    False
Name: Happiness Score_x, Length: 146, dtype: bool

In [60]:
y.isnull().sum()

Country                              0
Region_x                             0
Happiness Rank_x                     0
Happiness Score_x                    0
Standard Error                       0
Economy (GDP per Capita)_x           0
Family_x                             0
Health (Life Expectancy)_x           0
Freedom_x                            0
Trust (Government Corruption)_x      0
Generosity_x                         0
Dystopia Residual_x                  0
Region_y                             0
Happiness Rank_y                     0
Happiness Score_y                    0
Lower Confidence Interval            0
Upper Confidence Interval            0
Economy (GDP per Capita)_y           0
Family_y                             0
Health (Life Expectancy)_y           0
Freedom_y                            0
Trust (Government Corruption)_y      0
Generosity_y                         0
Dystopia Residual_y                  0
Happiness.Rank                       0
Happiness.Score                      0
Whisker.high                         0
Whisker.low                          0
Economy..GDP.per.Capita.             0
Family                               0
Health..Life.Expectancy.             0
Freedom                              0
Generosity                           0
Trust..Government.Corruption.        0
Dystopia.Residual                    0
col2                               111
dtype: int64

In [61]:
y['Country'].str.upper()

0      SWITZERLAND
1          ICELAND
2          DENMARK
3           NORWAY
4           CANADA
          ...
141         RWANDA
142          BENIN
143          SYRIA
144        BURUNDI
145           TOGO
Name: Country, Length: 146, dtype: object